name: Train ML Pipeline

on: 
  push:
    branches: [ "main", "master" ] # Runs when you push to the main branch
    
  pull_request:
    branches: [ "main", "master" ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Authenticate Google Drive
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Write the secret JSON to a temporary file
          echo "$GDRIVE_CREDENTIALS_DATA" > credentials.json
          
          # Tell DVC to use this service account file
          dvc remote modify myremote --local gdrive_use_service_account true
          dvc remote modify myremote --local gdrive_service_account_json_file_path credentials.json


      - name: Pull Data
        run: |
          # Try to pull up to 3 times in case Google Drive drops the connection
          dvc pull || dvc pull || dvc pull

      - name: Run ML Pipeline
        run: dvc repro


      # --- NEW CML STEPS BELOW ---
      
      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Create and Post CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Create a beautiful Markdown report
          echo "## ðŸ“Š Model Training Results" > report.md
          echo "Here are the final metrics for the latest model:" >> report.md
          
          # 2. Add the JSON metrics into a code block
          echo "\`\`\`json" >> report.md
          cat metrics.json >> report.md
          echo "\`\`\`" >> report.md
          
          # 3. Tell CML to post this report as a GitHub comment!
          cml comment create report.md
